version: 2

models:
  - name: cc_stock
    columns: 
        ### PK ###
      - name: product_id
        tests:
          - unique
      ### PK ###
      - name: product_name
        tests:
          - not_null
      ### PK ###
      - name: model_type
        tests:
          - not_null  
          - accepted_values:  
             values: ['T-shirt', 'Short', 'Legging', 'Crop-top', 'Top', 'Accessories']

          
