version: 2

models:
  - name: cc_stock
    columns: 
        ### PK ###
      - name: product_id
        tests:
          - unique
      ### PK ###
      - name: product_name
        tests:
          - not_null
      ### PK ###
      - name: model_name
        tests:
          - not_null     

          
